# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bainbridge Island Cub Scout Pack 4496
email: pack4496@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pack 4496 is the oldest Cub Scout Pack on Bainbridge Island, in existence for over 60 years. For boys in grades first through fifth, we are a parent-run organization dedicated to instilling the values of Scouting by giving our kids a combination of fun and educational experiences.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
encoding: utf-8
